language: ruby
rvm: 2.0.0

deploy: 
provider: heroku
app:
master: glacial-fjord-79432
api_key:
secure: BySHY26O4KkTo9/2/1AFLBEiEkp+tSL6Gzpk/Cwv890l3yU27sK3xyS+oVnNKZCvBYreuovq2jQtvDfeELGv+Ar3IIkji5s0VC0ZnlAUmy9qhIOnQE9qAZT7x9Uukq95m6EkErOMR/06A9M61zvkif4gMX18oSva0iZkaeEw+w8fQLrwPC0fgxutTP+2OidMDGcSwxYGklO0rZQH/dOIV/uYmZxGpJq0ePB7E8u5t/C3jcmdet+03CgH5MEsKC25wi0f02hUnlPhtwu3D44lmL8mk7o2/6lpC/xj4PQ8/5HqJbR5ZzhSguloj1iLCKA0P20w1msffaSWlOPEzG/bJJVuCv7T8VY/9U5SSJ4T/BjYyFXreIF+HwcbVnCsf1+ODKTtaM2etS6E5Qnhck4j6GowclNppF9b/z0UxecsfoOU7JK0f9EAz3m0Khop109Cws7FcEnmsMolA2DvDyyDO4JQnYFNpox68JxIyME/Mnk1WkRJrUJqOVwlObyJ/oeUiAV06RPm8WNWMl+Szc+2AD2a5Dgb7uJ7UbPcz3tfrD+WNVEwL/9RI7FIv7O5dvNvkXoX9N2gcxCD9rNMqKky/5NHvQt/lwwEP0LY3i1CQJFRVUIKLbLLyJvGq9WTLnE9neI+OW/Wkhv68dmszqWCuqErybMV0ma4WNMOBSRmDR8=